# Generated by Django 3.1.7 on 2021-05-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(default='not found...'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='not found...', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='typeOfJob',
            field=models.CharField(choices=[('Plumber', 'Plumber'), ('Carpenter', 'Carpenter'), ('Electrician', 'Electrician'), ('Testwork', 'Testwork')], default='not found...', max_length=100),
        ),
    ]
