# Generated by Django 3.1.7 on 2021-05-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default='not found...'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='not found...', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='typeOfJob',
            field=models.CharField(blank=True, choices=[('Plumber', 'Plumber'), ('Carpenter', 'Carpenter'), ('Electrician', 'Electrician'), ('Testwork', 'Testwork')], default='not found...', max_length=100),
        ),
    ]
